default: &default
  adapter: mysql2
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port:     <%= ENV.fetch("DATABASE_PORT") { 3306 } %>
  database: <%= ENV.fetch("DATABASE_NAME") { "location" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") {} %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: location_service_test