default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DATABASE_NAME") { "location_service" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "root" } %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  socket: /tmp/mysql.sock

development:
  <<: *default

test:
  <<: *default
  database: location_service_test